name: Fail Job Issue Demo
on: [push]
jobs:
  FailJobIssueDemo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Step is going to pass
        run: echo Passing step
      - name: Step is going to fail
        run: exit 1
      - uses: nashmaniac/create-issue-action@v1.1
        name: Create Issue Action
        with:
          title: Build Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: worflow-failed
          body: Workflow failed for commit ${{github.sha}}
