name: Fail Job Issue Demo
on: [push]
jobs:
  FailJobIssueDemo:
    runs-on: ubuntu-latest
    steps:
      - name: Step is going to pass
        run: echo Passing step
      - name: Step is going to fail
        run: exit 1
      - name: Step To run on failure
        if: ${{ failure() }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          assignees: ${{ github.actor }}
          milestone: 1
          update_existing: true
          search_existing: all
